config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:index, :show]
  resources :projects do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :schedules do
    resources :shares, only: [:create, :edit, :update, :destroy]
  end

  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user
  belongs_to :schedule
  has_many_attached :memo_files

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :hour

  with_options presence: true do
    validates :share_date
    validates :hour_id, numericality: {other_than: 1 , message: "can't be blank"}
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  before_action :set_share, only: [:edit, :update, :destroy]
  before_action :move_to_show, only: [:edit, :destroy]

  def create
    @share = Share.new(share_params)
    if @share.save
      redirect_to schedule_path(params[:schedule_id])
    else
      @schedule = Schedule.find(params[:schedule_id])
      @shares = @schedule.shares.includes(:user)
      @hour = 0
      @shares.each do |num|
        @hour += num.hour.name.to_f
      end
      @dat_week = ['SUN','MON','TUE','WED','THE','FRI','SAT']
      render 'schedules/show'
    end
  end

  def edit
    @schedule = Schedule.find(params[:schedule_id])
  end

  def update
    @share.memo_files.attach(params[:memo_files]) if @share.memo_files.blank?
    if @share.update(share_params)
      redirect_to schedule_path(params[:schedule_id])
    end
  end

  def destroy
    @share.destroy
    redirect_to schedule_path(params[:schedule_id])
  end

  private
  def share_params
    params.require(:share).permit(:share_date, :hour_id, :memo, {memo_files: []}).merge(user_id: current_user.id, schedule_id: params[:schedule_id])
  end

  def set_share
    @share = Share.find(params[:id])
  end

  def move_to_show
    redirect_to schedule_path(params[:schedule_id]) unless (user_signed_in? && current_user.id == @share.user_id)
  end
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/views/shares/_header.html.erb
<header>
  <h2><%= link_to image_tag("team_schedule_logo.png") , "/", data: {"turbolinks"=>false}, class:"header_logo" %></h2>
  <% if user_signed_in? %>
    <div class="hamburger_menu">
      <input type="checkbox" id="menu_btn_check">
      <label for="menu_btn_check" class="menu_btn"><span></span><span></span><span></span></label>
      <nav class="menu_content">
        <%= link_to "プロジェクト", projects_path, class: "header_list flex", id: "nav04", data: {"turbolinks"=>false} %>
        <%= link_to "スケジュール", schedules_path, class: "header_list flex", id: "nav05", data: {"turbolinks"=>false} %>
        <%= link_to "マイページ", user_path(current_user.id), class: "header_list flex", id: "nav06", data: {"turbolinks"=>false} %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_list _logout flex", data: {"turbolinks"=>false} %>
      </nav>
    </div>
  <% end %>
  <nav>
  <% if user_signed_in? %>
    <%= link_to "プロジェクト", projects_path, class: "header_list flex s-none", id: "nav01", data: {"turbolinks"=>false} %>
    <%= link_to "スケジュール", schedules_path, class: "header_list flex s-none", id: "nav02", data: {"turbolinks"=>false} %>
    <%= link_to "マイページ", user_path(current_user.id), class: "header_list flex s-none", id: "nav03", data: {"turbolinks"=>false} %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_list _logout flex s-none", data: {"turbolinks"=>false} %>
  <% else %>
    <%= link_to "新規登録", new_user_registration_path, class: "header_list flex", data: {"turbolinks"=>false} %>
  <% end %>
  </nav>
</header>

app/views/shares/_index.html.erb
<div class="share_box">
  <h4>作業工数合計： <strong class="f-en">
  <%= @hour %>h(<%= (@hour/8).round(1) %>day)
  </strong></h4>
  <ul class="shares_list">
    <% @shares.each do |share| %>
      <li class="share_id">
        <p class="f-en share_day">
          <%= share.share_date.strftime("%-m/%-d(#{@dat_week[share.share_date.wday]})") %>：<%= share.hour.name %>
          <span class="user-info f-def">
            <%= link_to user_path(share.user_id),data: {"turbolinks"=>false} do %>
              <%= share.user.nickname %>
            <% end %>
          </span>
        </p>
        <% if share.memo.presence %>
        <p class="share_memo"><%= safe_join(share.memo.split("\n"),tag(:br)) %></p>
        <% end %>
        <% if share.memo_files.presence %>
        <ul class="share_file">
          <% share.memo_files.each do |file| %>
            <% if file.representable? %>
              <li>
                <%= link_to rails_blob_path(file, disposition: "attachment") do %>
                  <%= image_tag file.representation(resize_to_limit: [320, 120]) %>
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to file.filename, rails_blob_path(file, disposition: "attachment") %>
              </li>
              <% end %>
          <% end %>
        </ul>
        <% end %>
        <% if (current_user.id == share.user_id) && (@schedule.end_date >= Date.today) %>
        <div class="share_edit_box">
          <input type="checkbox" id="share_edit_<%= share.id %>" class="none">
          <label for="share_edit_<%= share.id %>" class="edit_btn none m-flex"><span></span><span></span><span></span></label>
          <ul class="comment_edit">
            <li><%= link_to "削除", schedule_share_path(share.schedule_id, share.id), method: :delete, data: {"turbolinks"=>false} %></li>
            <li class="share_edit_btn"><%= link_to "編集", edit_schedule_share_path(share.schedule_id, share.id), remote: true %></li>
          </ul>
        </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/shares/_new.html.erb
<%= form_with model: [@schedule, @share], local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <p class="_required">作業日</p><br />
        <%= f.date_field :share_date, id: "project_start" %>
      </div>

      <div class="field">
        <p class="_required">上記日付の作業時間</p><br />
        <div class="form-list">
          <%= f.collection_select(:hour_id, Hour.all, :id, :name, {}, {class:"text_field"}) %>
        </div>
      </div>

      <div class="field">
        <p class="_any">作業メモ</p><br />
        <%= f.text_area :memo, class: "text_field _share" %>
      </div>

      <div class="field file_upload">
        <p class="_any">添付ファイル</p><br />
        <div class="file_btn">
          <%= f.file_field :memo_file, name: "share[memo_files][]", data: {index: 0} %>
        </div>
        <div class="file_btn">
          <%= f.file_field :memo_file, name: "share[memo_files][]", data: {index: 0} %>
        </div>
        <div class="file_btn">
          <%= f.file_field :memo_file, name: "share[memo_files][]", data: {index: 0} %>
        </div>
        <div class="file_btn">
          <%= f.file_field :memo_file, name: "share[memo_files][]", data: {index: 0} %>
        </div>
        <div class="file_btn">
          <%= f.file_field :memo_file, name: "share[memo_files][]", data: {index: 0} %>
        </div>
      </div>

      <div class="btn1 actions">
        <%= f.submit "上記の内容で確定する" %>
      </div>

    <% end %>

app/views/shares/edit.js.erb
$('#share_form').html('<%= j(render partial: 'shares/new') %>');