config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:index, :show]
  resources :projects do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :schedules do
    resources :shares, only: [:create, :edit, :update, :destroy]
  end

  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :project_users
  has_many :projects, through: :project_users
  has_many :shares
  has_many :comments

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :work

  VALID_PASS_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  
  with_options presence: true do
    validates :nickname, uniqueness: { case_sensitive: true }
    validates :work_id,  numericality: {other_than: 1 , message: "can't be blank"}
  end

  validates :password, format: { with: VALID_PASS_REGEX, message: "is invalid"}, allow_blank: true, unless: :project?
  validates :profile_text, {length: {maximum: 800}}

  def project?
    validation_context == :project
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index, only: [:index, :show]

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
    date = Date.today
    shares = @user.shares.where(share_date: [(date)..(date.since(6.days))]).order(share_date: "ASC")

    @today = Date.today-1
    num = 0
    i = 1
    7.times do
      num += 1
      unless (@today+num).saturday? || (@today+num).sunday?
        instance_variable_set("@day#{i}", @today + num)
        i += 1
      end
    end
    @dat_week = ['SUN','MON','TUE','WED','THE','FRI','SAT']
    1..5.times do |num|
      num += 1
      instance_variable_set("@share#{num}", [])
      instance_variable_set("@hour#{num}", 0)
    end
    shares.each do |share|
      if share.share_date == @day1
        @share1.push(share)
        @hour1 += share.hour.name.to_f
      elsif share.share_date == @day2
        @share2.push(share)
        @hour2 += share.hour.name.to_f
      elsif share.share_date == @day3
        @share3.push(share)
        @hour3 += share.hour.name.to_f
      elsif share.share_date == @day4
        @share4.push(share)
        @hour4 += share.hour.name.to_f
      elsif share.share_date == @day5
        @share5.push(share)
        @hour5 += share.hour.name.to_f
      end
    end
  end

  private
  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= render "shared/header"%>
<main class="_mypage wrapper">
  <%= link_to "戻る", request.referer, class: "return_link mypage_btn" %>
  <h2 class="member_all f-en ac">Members list</h2>
  <h3 class="member_ttl f-en">Director</h3>
  <ul class="member_lists">
    <% @user.each do |user| %>
      <% if user.work_id == 2 %>
      <li class="member">
        <%= link_to user_path(user.id), class: "member_link" do %>
          <div class="profile_img">
            <%= image_tag user.profile_image if user.profile_image.attached? %>
          </div>
          <span class="member_name"><%= user.nickname %></span>
        <% end %>

        <% unless Date.today.saturday? || Date.today.sunday? %>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>
          <% if (user.shares.where(share_date: Date.today).sum(:hour_id)) >= 5 %>
            <p class="f-en average_rate"><%= ((user.shares.where(share_date: Date.today).sum(:hour_id))*10/8) %></p>
          <% elsif (user.shares.where(share_date: Date.today).sum(:hour_id)) == 0 %>
            <p class="f-en average_rate">0</p>
          <% end %>
        </div>
        <% end %>
      </li>
      <% end %>
    <% end %>
  </ul>

  <h3 class="member_ttl f-en">Designer</h3>
  <ul class="member_lists">
    <% @user.each do |user| %>
      <% if user.work_id == 3 %>
      <li class="member">
        <%= link_to user_path(user.id), class: "member_link" do %>
          <div class="profile_img">
            <%= image_tag user.profile_image if user.profile_image.attached? %>
          </div>
          <span class="member_name"><%= user.nickname %></span>
        <% end %>

        <% unless Date.today.saturday? || Date.today.sunday? %>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>
          <% if (user.shares.where(share_date: Date.today).sum(:hour_id)) >= 5 %>
            <p class="f-en average_rate"><%= ((user.shares.where(share_date: Date.today).sum(:hour_id))*10/8) %></p>
          <% elsif (user.shares.where(share_date: Date.today).sum(:hour_id)) == 0 %>
            <p class="f-en average_rate">0</p>
          <% end %>
        </div>
        <% end %>
      </li>
      <% end %>
    <% end %>
  </ul>

  <h3 class="member_ttl f-en">Engineer</h3>
  <ul class="member_lists">

    <% @user.each do |user| %>
      <% if user.work_id == 4 %>
      <li class="member">
        <%= link_to user_path(user.id), class: "member_link" do %>
          <div class="profile_img">
            <%= image_tag user.profile_image if user.profile_image.attached? %>
          </div>
          <span class="member_name"><%= user.nickname %></span>
        <% end %>

        <% unless Date.today.saturday? || Date.today.sunday? %>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>

          <% if (user.shares.where(share_date: Date.today).sum(:hour_id)) >= 5 %>
            <p class="f-en average_rate"><%= ((user.shares.where(share_date: Date.today).sum(:hour_id))*10/8) %></p>
          <% elsif (user.shares.where(share_date: Date.today).sum(:hour_id)) == 0 %>
            <p class="f-en average_rate">0</p>
          <% end %>

        </div>
        <% end %>

      </li>
      <% end %>
    <% end %>

  </ul>
</main>
<%= render "shared/footer"%>

app/views/users/show.html.erb
<%= render "shared/header"%>
<main class="_mypage wrapper">
<%= link_to "戻る", request.referer, class: "return_link mypage_btn" %>
  <div class="profile_box">
    <div class="profile_img">
      <%= image_tag @user.profile_image if @user.profile_image.attached? %>
    </div>
    <section>
      <h3><%= @user.nickname %>さん <br class="none s-inline"><span id="my_work"><%= @user.work.name %></span></h3>
      <% if current_user.id == @user.id %>
      <div class="link_edit">
        <input type="checkbox" id="edit_btn_check" class="none">
        <label for="edit_btn_check" class="edit_btn none s-ib"><span></span><span></span><span></span></label>
        <div class="s-none"><%= link_to '編集', edit_user_registration_path %></div>
      </div>
      <% end %>
      <p class="s-none">
      <% if @user.profile_text.present? %>
        <%= safe_join(@user.profile_text.split("\n"),tag(:br)) %>
      <% end %>
      </p>
      <p class="profile_email none s-block">連絡先：<%= @user.email %></p>
    </section>
  </div>

  <p class="profile_email s-none">連絡先：<%= @user.email %></p>
  <p class="profile_txt none s-block">
  <% if @user.profile_text.present? %>
    <%= safe_join(@user.profile_text.split("\n"),tag(:br)) %>
    <% end %>
  </p>
  <div class="my_state">
    <ul class="slider">
      <li>
        <h4 class="f-en"><%= @day1.strftime("%-m/%-d(#{@dat_week[@day1.wday]})") %></h4>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>
          <p class="f-en average_rate"><%= (@hour1/8*100).round(1) %></p>
        </div>
        <ul class="share_mylist">
          <% @share1.each do |share| %>
          <li>・<%= share.schedule.project.name %>：<%= share.schedule.title %>（<%= share.hour.name %>）</li>
          <% end %>
        </ul>
      </li>
      <li>
        <h4 class="f-en"><%= @day2.strftime("%-m/%-d(#{@dat_week[@day2.wday]})") %></h4>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>
          <p class="f-en average_rate"><%= (@hour2/8*100).round(1) %></p>
        </div>
        <ul class="share_mylist">
          <% @share2.each do |share| %>
          <li>・<%= share.schedule.project.name %>：<%= share.schedule.title %>（<%= share.hour.name %>）</li>
          <% end %>
        </ul>
      </li>
      <li>
        <h4 class="f-en"><%= @day3.strftime("%-m/%-d(#{@dat_week[@day3.wday]})") %></h4>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>
          <p class="f-en average_rate"><%= (@hour3/8*100).round(1) %></p>
        </div>
        <ul class="share_mylist">
          <% @share3.each do |share| %>
          <li>・<%= share.schedule.project.name %>：<%= share.schedule.title %>（<%= share.hour.name %>）</li>
          <% end %>
        </ul>
      </li>
      <li>
        <h4 class="f-en"><%= @day4.strftime("%-m/%-d(#{@dat_week[@day4.wday]})") %></h4>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>
          <p class="f-en average_rate"><%= (@hour4/8*100).round(1) %></p>
        </div>
        <ul class="share_mylist">
          <% @share4.each do |share| %>
          <li>・<%= share.schedule.project.name %>：<%= share.schedule.title %>（<%= share.hour.name %>）</li>
          <% end %>
        </ul>
      </li>
      <li>
        <h4 class="f-en"><%= @day5.strftime("%-m/%-d(#{@dat_week[@day5.wday]})") %></h4>
        <div class="average_box">
          <div class="average"><div class="_fill"></div></div>
          <p class="f-en average_rate"><%= (@hour5/8*100).round(1) %></p>
        </div>
        <ul class="share_mylist">
          <% @share5.each do |share| %>
            <li>・<%= share.schedule.project.name %>：<%= share.schedule.title %>（<%= share.hour.name %>）</li>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>

  <ul class="links">
    <li><%= link_to "プロジェクト一覧", projects_path %></li>
    <li><%= link_to "プロジェクト新規作成", new_project_path %></li>
    <li><%= link_to "マイスケジュール", "/schedules?q%5Bwork_id_eq%5D=&q%5Bshares_user_id_eq%5D=#{@user.id}&q%5Bproject_name_or_title_or_shares_memo_cont%5D=&commit=検索" %></li>
    <li><%= link_to "スケジュール新規作成", new_schedule_path %></li>
  </ul>

  <%= link_to "メンバーリストはこちら", users_path, class: "other_users" %>
</main>
<%= render "shared/footer"%>