config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:index, :show]
  resources :projects do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :schedules do
    resources :shares, only: [:create, :edit, :update, :destroy]
  end

  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  has_many :shares, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :start_date
    validates :end_date
    validates :work_id, numericality: {other_than: 1 , message: "can't be blank"}
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :work

  validate :start_end_check

  def start_end_check
    if start_date.present? && end_date.present?
      errors.add(:end_date, "must be greater than Project start") unless
        self.start_date <= self.end_date
      end
    end
  # end

  scope :with_keywords, -> keywords {
    if keywords.present?
      squished_keywords = keywords.squish
      keywords = squished_keywords.split(" ")
      sch = Schedule.arel_table[:title]
      pro = Project.arel_table[:name]
      where(keywords.map {|keyword|
         sch.matches("%#{keyword}%").or( pro.matches("%#{keyword}%") )
      }.inject(:and))
    end
  }

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  def index
    @today = Date.today
    @monday = Date.today.beginning_of_week

    @q = Schedule.joins(:project).select('schedules.*, projects.name AS project_name').with_keywords(params.dig(:q, :keywords)).ransack(params[:q])
    @schedules = @q.result(distinct: true)

    @dat_week = ['SUN','MON','TUE','WED','THE','FRI','SAT']

    @holiday = []
    at_day = @today - 36
    105.times do 
      at_day += 1
      if HolidayJapan.check(at_day)
        @holiday.push(at_day)
      end
    end

    calendar_split

  end

  def new
    @schedule = Schedule.new
    referer = Rails.application.routes.recognize_path(request.referer)
    if (referer[:controller] == 'projects') && (referer[:action] == 'show')
      @id = referer[:id]
    end
  end

  def create
    @schedule = Schedule.new(schedule_params)
    if @schedule.save
      redirect_to schedules_path
    else
      render :new
    end
  end

  def show
    @shares = @schedule.shares.includes(:user).order('share_date')
    @share = Share.new

    @hour = 0
    @shares.each do |num|
      @hour += num.hour.name.to_f
    end
    @dat_week = ['SUN','MON','TUE','WED','THE','FRI','SAT']
  end

  def edit
  end

  def update
    if @schedule.update(schedule_params)
      redirect_to schedule_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @schedule.destroy
    redirect_to schedules_path
  end


  private
  def schedule_params
    params.require(:schedule).permit(:title, :start_date, :end_date, :work_id, :project_id)
  end

  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  def calendar_split
    base_week = @monday - 42

    1..15.times do |num|
      base_week = base_week + 7
      instance_variable_set("@base_week#{num}", base_week)
      instance_variable_set("@mon_schedule#{num}", [])
      instance_variable_set("@tue_schedule#{num}", [])
      instance_variable_set("@wed_schedule#{num}", [])
      instance_variable_set("@thu_schedule#{num}", [])
      instance_variable_set("@fri_schedule#{num}", [])
    end

    # 5週間前
    @schedules.each do |s|
      if (@base_week0.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule0.push(s)
      elsif ((@base_week0+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule0.push(s)
      elsif ((@base_week0+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule0.push(s)
      elsif ((@base_week0+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule0.push(s)
      elsif ((@base_week0+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule0.push(s)
      end
    end

    # 4週間前
    @schedules.each do |s|
      if (@base_week1.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule1.push(s)
      elsif ((@base_week1+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule1.push(s)
      elsif ((@base_week1+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule1.push(s)
      elsif ((@base_week1+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule1.push(s)
      elsif ((@base_week1+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule1.push(s)
      end
    end

    # 3週間前
    @schedules.each do |s|
      if (@base_week2.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule2.push(s)
      elsif ((@base_week2+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule2.push(s)
      elsif ((@base_week2+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule2.push(s)
      elsif ((@base_week2+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule2.push(s)
      elsif ((@base_week2+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule2.push(s)
      end
    end

    # 2週間前
    @schedules.each do |s|
      if (@base_week3.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule3.push(s)
      elsif ((@base_week3+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule3.push(s)
      elsif ((@base_week3+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule3.push(s)
      elsif ((@base_week3+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule3.push(s)
      elsif ((@base_week3+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule3.push(s)
      end
    end

    # 1週間前
    @schedules.each do |s|
      if (@base_week4.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule4.push(s)
      elsif ((@base_week4+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule4.push(s)
      elsif ((@base_week4+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule4.push(s)
      elsif ((@base_week4+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule4.push(s)
      elsif ((@base_week4+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule4.push(s)
      end
    end

    # 今週
    @schedules.each do |s|
      if (@base_week5.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule5.push(s)
      elsif ((@base_week5+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule5.push(s)
      elsif ((@base_week5+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule5.push(s)
      elsif ((@base_week5+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule5.push(s)
      elsif ((@base_week5+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule5.push(s)
      end
    end

    # 来週
    @schedules.each do |s|
      if (@base_week6.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule6.push(s)
      elsif ((@base_week6+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule6.push(s)
      elsif ((@base_week6+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule6.push(s)
      elsif ((@base_week6+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule6.push(s)
      elsif ((@base_week6+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule6.push(s)
      end
    end

    # 2週間後
    @schedules.each do |s|
      if (@base_week7.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule7.push(s)
      elsif ((@base_week7+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule7.push(s)
      elsif ((@base_week7+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule7.push(s)
      elsif ((@base_week7+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule7.push(s)
      elsif ((@base_week7+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule7.push(s)
      end
    end

    # 3週間後
    @schedules.each do |s|
      if (@base_week8.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule8.push(s)
      elsif ((@base_week8+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule8.push(s)
      elsif ((@base_week8+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule8.push(s)
      elsif ((@base_week8+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule8.push(s)
      elsif ((@base_week8+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule8.push(s)
      end
    end

    # 4週間後
    @schedules.each do |s|
      if (@base_week9.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule9.push(s)
      elsif ((@base_week9+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule9.push(s)
      elsif ((@base_week9+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule9.push(s)
      elsif ((@base_week9+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule9.push(s)
      elsif ((@base_week9+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule9.push(s)
      end
    end

    # 5週間後
    @schedules.each do |s|
      if (@base_week10.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule10.push(s)
      elsif ((@base_week10+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule10.push(s)
      elsif ((@base_week10+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule10.push(s)
      elsif ((@base_week10+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule10.push(s)
      elsif ((@base_week10+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule10.push(s)
      end
    end

    # 6週間後
    @schedules.each do |s|
      if (@base_week11.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule11.push(s)
      elsif ((@base_week11+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule11.push(s)
      elsif ((@base_week11+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule11.push(s)
      elsif ((@base_week11+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule11.push(s)
      elsif ((@base_week11+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule11.push(s)
      end
    end

    # 7週間後
    @schedules.each do |s|
      if (@base_week12.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule12.push(s)
      elsif ((@base_week12+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule12.push(s)
      elsif ((@base_week12+2) == (Date.parse(s[:start_date].to_s)))
        @wed_schedule12.push(s)
      elsif ((@base_week12+3) == (Date.parse(s[:start_date].to_s)))
        @thu_schedule12.push(s)
      elsif ((@base_week12+4) == (Date.parse(s[:start_date].to_s)))
        @fri_schedule12.push(s)
      end
    end

    # 8週間後
    @schedules.each do |s|
      if (@base_week13.between?(Date.parse(s[:start_date].to_s), Date.parse(s[:end_date].to_s)))
        @mon_schedule13.push(s)
      elsif ((@base_week13+1) == (Date.parse(s[:start_date].to_s)))
        @tue_schedule13.push(s)

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with model: @schedule, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <p class="_required">プロジェクトを選択する</p><br />
        <div class="form-list">
        <% if @id.presence %>
          <%= f.collection_select :project_id, Project.where("project_end >= ?", Date.today), :id, :name, {selected: @id}, {class:"text_field", id:"work-list"} %>
        <% else %>
          <%= f.collection_select :project_id, Project.where("project_end >= ?", Date.today), :id, :name, {prompt: "選択してください"}, {class:"text_field", id:"work-list"} %>
        <% end %>
        </div>
      </div>

      <div class="field">
        <p class="_required">作業タイトル</p><br />
        <%= f.text_field :title, class: "text_field" %>
      </div>

      <div class="field">
        <p class="_required">作業開始日</p><br />
        <%= f.date_field :start_date, id: "project_start" %>
      </div>

      <div class="field">
        <p class="_required">作業締切日</p><br />
        <%= f.date_field :end_date, id: "project_end" %>
      </div>

      <div class="field">
        <p class="_required">作業内容の役職を選択する</p><br />
        <div class="form-list">
          <%= f.collection_select(:work_id, Work.all, :id, :name, {}, {class:"text_field", id:"work-list"}) %>
        </div>
      </div>

      <div class="btn1 actions">
        <%= f.submit "上記の内容で確定する" %>
      </div>

    <% end %>

app/views/schedules/edit.html.erb
<%= render "shared/header"%>

<main class="_schedule _form">
  <div class="ttl">
    <%= link_to "戻る", request.referer, class: "return_link" %>
    <h4>スケジュール編集</h4>
  </div>
  <div class="schedule_form">
  <%= render "form"%>
  </div>
</main>

<%= render "shared/footer"%>

app/views/schedules/index.html.erb
<%= render "shared/header"%>

<main class="_schedule">
<div class="search_box">
  <div class="ttl">
    <p class="project_acco_btn none s-block">検索する<span></span></p>
    <%= search_form_for @q do |f| %>
      <div class="search_input">
        <%= f.label :work_id_eq, "役職名を選択" %><br>
        <div class="search_input_list">
          <%= f.collection_select :work_id_eq, Work.where.not(id: 1), :id, :name, include_blank: '指定なし' %>
        </div>
        
      </div>
      <div class="search_input">
        <%= f.label :shares_user_id_eq, "ユーザー名を選択" %><br>
        <div class="search_input_list">
          <%= f.collection_select :shares_user_id_eq, User.all, :id, :nickname, include_blank: '指定なし' %>
        </div>
      </div>
      <div class="search_input">
        <%= f.label :keywords, "キーワードを入力" %><br>
        <div class="search_input_keyword">
        <%= f.text_field :keywords, value: params[:q]&.dig(:keywords) %>
        </div>
      </div>
      <div class="search_submit">
        <%= f.submit "検索" %> 
      </div>
    <% end %>
    <%= link_to '作成する', new_schedule_path, class: "link_new"  %>
  </div>
</div>

  <p id="today" style="display:none;"><%= @today.strftime("%-m/%-d(#{@dat_week[@today.wday]})") %></p>
  <% @holiday.each do |day| %>
    <p class="holiday" style="display:none;"><%= day.strftime("%-m/%-d(#{@dat_week[day.wday]})") %></p>
  <% end %>

    <div class="accordion_btn" id="btn_top"><span>前の週をみる</span></div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week0, mon_schedule: @mon_schedule0, tue_schedule: @tue_schedule0, wed_schedule: @wed_schedule0, thu_schedule: @thu_schedule0, fri_schedule: @fri_schedule0} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week1, mon_schedule: @mon_schedule1, tue_schedule: @tue_schedule1, wed_schedule: @wed_schedule1, thu_schedule: @thu_schedule1, fri_schedule: @fri_schedule1} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week2, mon_schedule: @mon_schedule2, tue_schedule: @tue_schedule2, wed_schedule: @wed_schedule2, thu_schedule: @thu_schedule2, fri_schedule: @fri_schedule2} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week3, mon_schedule: @mon_schedule3, tue_schedule: @tue_schedule3, wed_schedule: @wed_schedule3, thu_schedule: @thu_schedule3, fri_schedule: @fri_schedule3} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week4, mon_schedule: @mon_schedule4, tue_schedule: @tue_schedule4, wed_schedule: @wed_schedule4, thu_schedule: @thu_schedule4, fri_schedule: @fri_schedule4} %>
    </div>
    <div class="accordion_list _look">
      <%= render 'schedule', { base_week: @base_week5, mon_schedule: @mon_schedule5, tue_schedule: @tue_schedule5, wed_schedule: @wed_schedule5, thu_schedule: @thu_schedule5, fri_schedule: @fri_schedule5} %>
    </div>
    <div class="accordion_list _look">
      <%= render 'schedule', { base_week: @base_week6, mon_schedule: @mon_schedule6, tue_schedule: @tue_schedule6, wed_schedule: @wed_schedule6, thu_schedule: @thu_schedule6, fri_schedule: @fri_schedule6} %>
    </div>
    <div class="accordion_list _look">
      <%= render 'schedule', { base_week: @base_week7, mon_schedule: @mon_schedule7, tue_schedule: @tue_schedule7, wed_schedule: @wed_schedule7, thu_schedule: @thu_schedule7, fri_schedule: @fri_schedule7} %>
    </div>
    <div class="accordion_list _look">
      <%= render 'schedule', { base_week: @base_week8, mon_schedule: @mon_schedule8, tue_schedule: @tue_schedule8, wed_schedule: @wed_schedule8, thu_schedule: @thu_schedule8, fri_schedule: @fri_schedule8} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week9, mon_schedule: @mon_schedule9, tue_schedule: @tue_schedule9, wed_schedule: @wed_schedule9, thu_schedule: @thu_schedule9, fri_schedule: @fri_schedule9} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week10, mon_schedule: @mon_schedule10, tue_schedule: @tue_schedule10, wed_schedule: @wed_schedule10, thu_schedule: @thu_schedule10, fri_schedule: @fri_schedule10} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week11, mon_schedule: @mon_schedule11, tue_schedule: @tue_schedule11, wed_schedule: @wed_schedule11, thu_schedule: @thu_schedule11, fri_schedule: @fri_schedule11} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week12, mon_schedule: @mon_schedule12, tue_schedule: @tue_schedule12, wed_schedule: @wed_schedule12, thu_schedule: @thu_schedule12, fri_schedule: @fri_schedule12} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week13, mon_schedule: @mon_schedule13, tue_schedule: @tue_schedule13, wed_schedule: @wed_schedule13, thu_schedule: @thu_schedule13, fri_schedule: @fri_schedule13} %>
    </div>
    <div class="accordion_list">
      <%= render 'schedule', { base_week: @base_week14, mon_schedule: @mon_schedule14, tue_schedule: @tue_schedule14, wed_schedule: @wed_schedule14, thu_schedule: @thu_schedule14, fri_schedule: @fri_schedule14} %>
    </div>
    <div class="accordion_btn" id="btn_bottom"><span>次の週をみる</span></div>

</main>

<%= render "shared/footer"%>

app/views/schedules/new.html.erb
<%= render "shared/header"%>

<main class="_schedule _form">
  <div class="ttl">
    <%= link_to "戻る", request.referer, class: "return_link" %>
    <h4>スケジュール作成</h4>
  </div>
  <div class="schedule_form">
  <% unless Project.count == 0 %>
    <%= render "form"%>
  <% else %>
    <div class="non_form">
      <h4>プロジェクトが未作成です</h4>
      <p>まずはプロジェクトを作成しましょう！</p>
      <%= link_to "プロジェクト作成", new_project_path %>
    </div>
  <% end %>
  </div>
</main>

<%= render "shared/footer"%>

app/views/schedules/show.html.erb
<%= render "shares/header"%>
<main class="_schedule">

<div class="schedule_about_bg">
  <div class="schedule_about">
    <%= link_to "戻る", request.referer, class: "return_link", data: {"turbolinks"=>false} %>
    <h3><span><%= link_to @schedule.project.name, project_path(@schedule.project_id) %></span><br>
    <%= @schedule.title %></h3>

    <div class="schedule_edit_box">
      <input type="checkbox" id="schedule_edit_check" class="none">
      <label for="schedule_edit_check" class="edit_btn none m-flex"><span></span><span></span><span></span></label>
      <ul class="edit_links flex m-none">
        <li><%= link_to "削除", schedule_path(@schedule.id), method: :delete, data: {"turbolinks"=>false} %></li>
        <li><%= link_to "編集", edit_schedule_path(@schedule.id) %></li>
      </ul>
    </div>

    <h5 class="edit_time">最終更新日：<br class="l-none"><%= @schedule.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></h5>
    <p>
      <% if @schedule.work_id == 2 %>
      <span class="_director"><%= @schedule.work.name %></span>
      <% elsif @schedule.work_id == 3 %>
      <span class="_designer"><%= @schedule.work.name %></span>
      <% elsif @schedule.work_id == 4 %>
      <span class="_engineer"><%= @schedule.work.name %></span>
      <% end %>
      <%= @schedule.start_date %> 〜 <%= @schedule.end_date %>
    </p>
  </div>
</div>
  
  
  <h3 class="shares_ttl"><span>実稼働日メモ</span></h3>
  <% unless @schedule.end_date < Date.today %>
  <a href="#share_form" class="shares_anch none s-block">メモを投稿する</a>
  <div class="shares_wrapper">
    <div class="share_form" id="share_form">
      <%= render "shares/new" %>
    </div>
    <div class="person_hour_half">
      <%= render "shares/index"%>
    </div>
  </div>
  <% else %>
  <div class="shares_wrapper">
    <div class="person_hour">
      <%= render "shares/index"%>
    </div>
  </div>
   <% end %>
  

</main>
<%= render "shared/footer"%>