config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :users, only: [:index, :show]
  resources :projects do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :schedules do
    resources :shares, only: [:create, :edit, :update, :destroy]
  end

  # get '*not_found', to: 'application#routing_error'
  # post '*not_found', to: 'application#routing_error'
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :files
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  has_many :schedules, dependent: :destroy
  has_many :comments, dependent: :destroy

  with_options presence: true, if: -> { validation_context == :project} do
    validates :name
    validates :project_start
    validates :project_end
    validates :member_flag
  end

  validate :start_end_check, on: :project

  def start_end_check
    if project_start.present? && project_end.present?
      errors.add(:project_end, "must be greater than Project start") unless
        self.project_start <= self.project_end
    end 
  end

  scope :with_keywords, -> keywords {
    if keywords.present?
      squished_keywords = keywords.squish
      keywords = squished_keywords.split(" ")
      name = Project.arel_table[:name]
      about = Project.arel_table[:about]
      where(keywords.map {|keyword|
        name.matches("%#{keyword}%").or( about.matches("%#{keyword}%") )
      }.inject(:and))
    end
  }

  include FlagShihTzu

  has_flags(
    1 => :member_wanted,
    :column => 'member_flag'
  )
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :move_to_show, only: [:edit, :update, :destroy]

  def index
    @q = Project.with_keywords(params.dig(:q, :keywords)).ransack(params[:q])
    projects = @q.result(distinct: true)

    @project_after = projects.where("project_start > ?", Date.today)
    @project_now = projects.where("project_start <= ? and project_end >= ?", Date.today, Date.today)

    @project_before = []
    projects.each do |project|
      if Date.today.between?( project[:project_end] + 1 , (project[:project_end] + 40))
        @project_before.push(project)
      end
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save(context: :project)
      redirect_to projects_path
    else
      render :new
    end
  end

  def show
    @comments = @project.comments.includes(:user).order(id: :desc)
    @comment = Comment.new
    designer = @project.schedules.includes(:shares).where(work_id: '3')
    engineer = @project.schedules.includes(:shares).where(work_id: '4')

    @share_designer = 0
    designer.each do |d|
      d.shares.each do |share|
        @share_designer += share.hour.name.to_f
      end
    end

    @share_engineer = 0
    engineer.each do |e|
      e.shares.each do |share|
        @share_engineer += share.hour.name.to_f
      end
    end

    @sum = (@share_designer + @share_engineer) * 0.15
  end

  def edit
  end

  def update
    @project.files.attach(params[:files]) if @project.files.blank?

    @project.attributes = project_params
    if @project.save(context: :project)
      redirect_to project_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :about, :project_start, :project_end, {files: []}, {user_ids: []}, :member_flag)
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def move_to_show
      redirect_to action: :show unless (user_signed_in? && current_user.id == @project.users.ids[0])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<%= render "shared/header"%>

<main class="_project _form">
  <div class="ttl">
    <%= link_to "戻る", request.referer, class: "return_link project_btn" %>
    <h4>プロジェクト編集</h4>
  </div>
  <div class="project_form">
    <%= form_with model: @project, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <p class="_required">プロジェクト名</p><br />
        <%= f.text_field :name, autofocus: true, class: "text_field" %>
      </div>

      <div class="field">
        <p class="_any">プロジェクト内容</p><br />
        <%= f.text_area :about, class: "text_field _about", maxlength: 800, size: "20x6" %>
      </div>

      <div class="field file_upload">
        <p class="_any">添付ファイル<br /></p><br />
        <p class="_note">※変更・追加される際は、前回登録したデータが消えてしまいますので、必要なデータは再度ご登録をお願いいたします。</p>
        <div class="file_btn">
          <% if @project.files[0].present? %>
          <p>元データ：<%= @project.files[0].filename %></p>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% else %>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% end %>
        </div>
        <div class="file_btn">
          <% if @project.files[1].present? %>
          <p>元データ：<%= @project.files[1].filename %></p>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% else %>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% end %>
        </div>
        <div class="file_btn">
          <% if @project.files[2].present? %>
          <p>元データ：<%= @project.files[2].filename %></p>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% else %>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% end %>
        </div>
        <div class="file_btn">
          <% if @project.files[3].present? %>
          <p>元データ：<%= @project.files[3].filename %></p>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% else %>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% end %>
        </div>
        <div class="file_btn">
          <% if @project.files[4].present? %>
          <p>元データ：<%= @project.files[4].filename %></p>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% else %>
          <%= f.file_field :file, id:"project_files", name: "project[files][]" %>
          <% end %>
        </div>
      </div>

      <div class="field">
        <p class="_required">プロジェクト開始日</p><br />
        <%= f.date_field :project_start, id: "project_start" %>
      </div>

      <div class="field">
        <p class="_required">プロジェクトFIX予定日</p><br />
        <%= f.date_field :project_end, id: "project_end" %>
      </div>

      <div class="field">
        <p class="_any">メンバーを選択</p><br />
        <input type="hidden" name="project[user_ids][]" value=<%= current_user.id %>>
        <div id="check_member">
        <%= f.collection_check_boxes :user_ids, User.where.not(id: current_user.id), :id, :nickname, {include_hidden: false} %>
        </div>
      </div>

      <div class="field">
        <p class="_any">メンバー募集フラグ</p><br />
        <div class="flag_box">
          <div id="flag_field"></div>
          <%= f.check_box :member_flag %>
        </div>
      </div>

      <div class="btn1 actions">
        <%= f.submit "上記の内容に変更する" %>
      </div>
    <% end %>
  </div>
</main>

<%= render "shared/footer" %>

app/views/projects/index.html.erb
<%= render "shared/header"%>
<main class="_project">
  <div class="search_box">
    <div class="ttl">
    <p class="project_acco_btn none s-block">検索する<span></span></p>
    <%= search_form_for @q do |f| %>
      <div class="search_input">
        <%= f.label :users_id_eq, "ユーザー名を選択" %><br>
        <div class="search_input_list">
          <%= f.collection_select :users_id_eq, User.all, :id, :nickname, include_blank: '指定なし' %>
        </div>
      </div>
      <div class="search_input">
        <%= f.label :keywords, "キーワードを入力" %><br>
        <div class="search_input_keyword">
        <%= f.text_field :keywords, value: params[:q]&.dig(:keywords) %>
        </div>
      </div>
      <div class="search_submit">
        <%= f.submit "検索" %> 
      </div>
    <% end %>
    <%= link_to "プロジェクト作成", new_project_path, class: "link_new" %>
    </div>
  </div>
  <div class="project_all">
  <ul class="project_phase_list">
    <li id="phase_all" class="phase_btn">全て</li>
    <li id="phase_after" class="phase_btn">今後の予定</li>
    <li id="phase_now" class="phase_btn">進行中</li>
    <li id="phase_before" class="phase_btn">FIX</li>
  </ul>
    <section class="project_box _after none l-block" id="phase_after_sec">
      <h4>今後の予定<span><%= @project_after.count %></span></h4>
      <ul>
      <% @project_after.each do |project| %>
        <li class="">
          <%= link_to project_path(project.id) do %>
            <% if project.member_flag == 1 %>
              <div class="member_flag">メンバー募集中</div>
            <% end %>
            <h5><%= project.name %></h5>
            <p><%= project.project_start %> 〜 <%= project.project_end %></p>
            <div class="project_member">
            <% if project.users.count < 7 %>
              <% project.users.each do |member| %>
              <div class="_image"><%= image_tag member.profile_image if member.profile_image.attached? %><span><%= member.nickname %></span></div>
              <% end %>
            <% elsif project.users.count >= 7 %>
              <% project.users.first(6).each do |member| %>
              <div class="_image"><%= image_tag member.profile_image if member.profile_image.attached? %><span><%= member.nickname %></span></div>
              <% end %>
              <p>and<br>more.</p>
            <% end %>
            </div>
            <% end %>
        </li>
      <% end %>
      </ul>
    </section>
    <section class="project_box _now none l-block" id="phase_now_sec">
      <h4>進行中<span><%= @project_now.count %></span></h4>
      <ul>
      <% @project_now.each do |project| %>
        <li class="">
          <%= link_to project_path(project.id) do %>
            <% if project.member_flag == 1 %>
              <div class="member_flag">メンバー募集中</div>
            <% end %>
            <h5><%= project.name %></h5>
            <p><%= project.project_start %> 〜 <%= project.project_end %></p>
            <div class="project_member">
            <% if project.users.count < 7 %>
              <% project.users.each do |member| %>
              <div class="_image"><%= image_tag member.profile_image if member.profile_image.attached? %><span><%= member.nickname %></span></div>
              <% end %>
            <% elsif project.users.count >= 7 %>
              <% project.users.first(6).each do |member| %>
              <div class="_image"><%= image_tag member.profile_image if member.profile_image.attached? %><span><%= member.nickname %></span></div>
              <% end %>
              <p>and<br>more.</p>
            <% end %>
            </div>
            <% end %>
        </li>
      <% end %>
      </ul>
    </section>
    <section class="project_box _before none l-block" id="phase_before_sec">
      <h4>FIX<span><%= @project_before.count %></span></h4>
      <ul>
      <% @project_before.each do |project| %>
        <li class="">
          <%= link_to project_path(project.id) do %>
            <% if project.member_flag == 1 %>
              <div class="member_flag">メンバー募集中</div>
            <% end %>
            <h5><%= project.name %></h5>
            <p><%= project.project_start %> 〜 <%= project.project_end %></p>
            <div class="project_member">
            <% if project.users.count < 7 %>
              <% project.users.each do |member| %>
              <div class="_image"><%= image_tag member.profile_image if member.profile_image.attached? %><span><%= member.nickname %></span></div>
              <% end %>
            <% elsif project.users.count >= 7 %>
              <% project.users.first(6).each do |member| %>
              <div class="_image"><%= image_tag member.profile_image if member.profile_image.attached? %><span><%= member.nickname %></span></div>
              <% end %>
              <p>and<br>more.</p>
            <% end %>
            </div>
            
            <% end %>
        </li>
      <% end %>
      </ul>
    </section>
  </div>

</main>
<%= render "shared/footer"%>

app/views/projects/new.html.erb
<%= render "shared/header"%>
<main class="_project _form">
  <div class="ttl">
    <%= link_to "戻る", request.referer, class: "return_link project_btn" %>
    <h4>プロジェクト新規作成</h4>
  </div>

  <div class="project_form">
    <%= form_with model: @project, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

      <div class="field">
        <p class="_required">プロジェクト名</p><br />
        <%= f.text_field :name, autofocus: true, class: "text_field" %>
      </div>

      <div class="field">
        <p class="_any">プロジェクト内容</p><br />
        <%= f.text_area :about, class: "text_field _about", maxlength: 800, size: "20x6" %>
      </div>

      <div class="field file_upload">
        <p class="_any">添付ファイル</p><br />
        <div class="file_btn">
          <%= f.file_field :file, name: "project[files][]", data: {index: 0}, id: 'project_file_0' %>
        </div>
        <div class="file_btn">
          <%= f.file_field :file, name: "project[files][]", data: {index: 1}, id: 'project_file_1' %>
        </div>
        <div class="file_btn">
          <%= f.file_field :file, name: "project[files][]", data: {index: 2}, id: 'project_file_2' %>
        </div>
        <div class="file_btn">
          <%= f.file_field :file, name: "project[files][]", data: {index: 3}, id: 'project_file_3' %>
        </div>
        <div class="file_btn">
          <%= f.file_field :file, name: "project[files][]", data: {index: 4}, id: 'project_file_4' %>
        </div>
      </div>

      <div class="field">
        <p class="_required">プロジェクト開始日</p><br />
        <%= f.date_field :project_start, id: "project_start" %>
      </div>

      <div class="field">
        <p class="_required">プロジェクトFIX予定日</p><br />
        <%= f.date_field :project_end, id: "project_end" %>
      </div>

      <div class="field">
        <p class="_any">メンバーを選択</p><br />
        <input type="hidden" name="project[user_ids][]" value=<%= current_user.id %>>
        <div id="check_member">
        <%= f.collection_check_boxes :user_ids, User.where.not(id: current_user.id), :id, :nickname, {include_hidden: false} %>
        </div>
      </div>

      <div class="field">
        <p class="_any">メンバー募集フラグ</p><br />
        <div class="flag_box">
          <div id="flag_field"></div>
          <%= f.check_box :member_flag %>
        </div>
      </div>

      <div class="btn1 actions">
        <%= f.submit "上記の内容で作成する" %>
      </div>
    <% end %>
  </div>
</main>
<%= render "shared/footer"%>

app/views/projects/show.html.erb
<%= render "shares/header"%>

<main class="_project">
  <div class="ttl">
    <%= link_to "戻る", request.referer, class: "return_link project_btn", data: {"turbolinks"=>false} %>
    <h3><%= @project.name %></h3>
      <% if current_user.id == @project.project_users.first.user_id %>
      <div class="link_edit project_btn">
        <input type="checkbox" id="edit_btn_check" class="none">
        <label for="edit_btn_check" class="edit_btn none m-ib"><span></span><span></span><span></span></label>
        <ul class="edit_links none">
          <li><%= link_to "削除", project_path(@project.id), method: :delete, data: {"turbolinks"=>false} %></li>
          <li><%= link_to "編集", edit_project_path(@project.id), data: {"turbolinks"=>false} %></li>
        </ul>
      </div>
      <ul class="edit_links flex m-none">
          <li><%= link_to "削除", project_path(@project.id), method: :delete, class: 'project_btn', data: {"turbolinks"=>false} %></li>
          <li><%= link_to "編集", edit_project_path(@project.id), class: 'project_btn', data: {"turbolinks"=>false} %></li>
        </ul>
      <% end %>
  </div>
  <section class="wrapper _project_about">
    <div class="project_date">
      <p><span>開始日</span><%= @project.project_start %></p>
      <p><span>FIX予定日</span><%= @project.project_end %></p>
      <div class="project_author">
        <p>最終更新日：<%= @project.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></p>
        <% @project.users.first(1).each do |member| %>
          <p>作成者：<%= member.nickname %></p>
        <% end %>
      </div>
      <% if @project.project_end >= Date.today %>
        <%= link_to new_schedule_path, class: "project_schedule", data: {"turbolinks"=>false} do %>
          <p>このプロジェクトの<br>詳細スケジュールを設定する</p>
        <% end %>
      <% end %>
    </div>

    <div class="project_about">
      <p><%= safe_join(@project.about.split("\n"),tag(:br)) %><p>
    </div>

    <ul class="project_file">
    <% @project.files.each do |file| %>
      <% if file.representable? %>
      <li>
        <%= link_to rails_blob_path(file, disposition: "attachment"), data: {"turbolinks"=>false} do %>
          <%= image_tag file.representation(resize_to_limit: [400, 200]) %>
        <% end %>
      </li>
      <% else %>
      <li>
        <%= link_to file.filename, rails_blob_path(file, disposition: "attachment") %>
      </li>
      <% end %>
    <% end %>
    </ul>

    <div class="project_remark">
      <dl class="project_member">
      <dt><span>プロジェクトメンバー</span></dt>
      <% @project.users.each do |member| %>
      <dd>
        <div class="_image"><%= image_tag member.profile_image if member.profile_image.attached? %></div>
        <%= link_to member.nickname, user_path(member.id), data: {"turbolinks"=>false} %>
      </dd>
      <% end %>
    </dl>
    <dl class="project_hour">
      <dt><span>プロジェクト工数</span></dt>
      <dd>
        <h5>合計</h5>
        <p class="f-en"><%= @share_designer + @share_engineer + @sum %><small>day</small></p>
      </dd>
      <dd>
        <h5>デザイナー工数</h5>
        <p class="f-en"><%= @share_designer %><small>day</small></p>
      </dd>
      <dd>
        <h5>エンジニア工数</h5>
        <p class="f-en"><%= @share_engineer %><small>day</small></p>
      </dd>
      <dd>
        <h5>進捗管理(15%)</h5>
        <p class="f-en"><%= @sum %><small>day</small></p>
      </dd>
    </dl>
    </div>

    <section class="comment_box">
      <h3>コメント欄</h3>
      <div id="comment_form">
        <%= render "comments/new" %>
      </div>
      <ul class="comment_list">
      <% @comments.each do |comment| %>
        <li>
          <div class="comment_user">
            <p>from: <%= comment.user.nickname %><span><%= comment.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></span></p>
          </div>
          <p class="comment_text"><%= comment.text %></p>

          <% if current_user.id == comment.user_id %>
          <div class="comment_edit_box">
            <input type="checkbox" id="comment_edit_check" class="none">
            <label for="comment_edit_check" class="edit_btn none m-ib"><span></span><span></span><span></span></label>
            <ul class="comment_edit">
              <li><%= link_to "編集", edit_project_comment_path(comment.project_id, comment.id), remote: true %></li>
              <li><%= link_to "削除", project_comment_path(comment.project_id, comment.id), method: :delete, data: {"turbolinks"=>false} %></li>
            </ul>
          </div>
          <% end %>

        </li>
        <% end %>
      </ul>
    </section>
  </section>
</main>

<%= render "shared/footer"%>